<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;

/**
 * Fetches One Piece Card Game catalog data from a pinned commit of
 * buhbbl/punk-records (a static JSON dataset generated by the vegapull
 * scraper from Bandai's official card list, en.onepiece-cardgame.com) and
 * writes it out as the same 5-CSV format cardora:binder-import-v2
 * consumes, plus releases/release_memberships — it does NOT write to the
 * database itself.
 *
 * Canonical identity, release-aware (NOT suffix-only — an audit of the
 * real data found `_p` and `_r` suffixes are not a clean semantic split:
 * both appear interleaved under the same reprint product, and `_p`
 * variants sometimes live in a completely different real pack than their
 * base card):
 *
 *   binder_card         = base card number + gameplay identity (name,
 *                          cost, power, effect, types...). One canonical
 *                          card per base number, regardless of how many
 *                          packs/suffixes reference it.
 *   binder_card_variant = every distinct physical object seen for that
 *                          base number (the plain base id, every `_pN`,
 *                          every `_rN`) — one variant per distinct
 *                          source_variant_id. source_variant_kind
 *                          ("base"|"p"|"r") is kept as metadata only,
 *                          never decides canonical identity.
 *   release membership  = variant-level (binder_card_release_memberships.
 *                          variant_id), created only when a variant's
 *                          real (non-catch-all) pack differs from the
 *                          card's own home pack — e.g. a Premium Booster's
 *                          own parallel/reprint art of an older Starter
 *                          Deck card.
 *
 * Two source "packs" — 569801 "Other Product Card" and 569901 "Promotion
 * card" — are Bandai's own catch-all buckets for loose/promo
 * distribution, not real products. They never become a binder_release and
 * never decide a card's home pack; an appearance there is recorded as
 * provenance only (external_id rows), and when the SAME exact
 * source_variant_id + image appears in both buckets (found once:
 * OP07-091_p1), it becomes exactly one variant with both bucket
 * references kept as provenance, not two printings. A base number with NO
 * real home pack (75 found — English promo cards only ever distributed
 * loose) still gets a normal canonical card, homed in one synthetic
 * merged "catch-all" Set (not either individual bucket, and not a real
 * release) so the schema's required set_id is satisfied without
 * fabricating a product claim.
 *
 * Dry-run by default: always generates the CSVs + a global validation
 * report. Pass --apply to additionally hand the generated directory to
 * cardora:binder-import-v2, and only if the report is PASS or
 * PASS_WITH_WARNINGS.
 */
class ImportOnePiece extends Command
{
    protected $signature = 'cardora:onepiece-import
        {--out= : Directory to write games/sets/cards/variants/external_ids/releases/release_memberships CSVs into (default: storage/app/onepiece)}
        {--apply : Also run cardora:binder-import-v2 on the generated CSVs. Only runs on PASS or PASS_WITH_WARNINGS. Without this flag nothing touches the database.}
        {--refresh-cache : Ignore the persistent on-disk cache and re-download from GitHub (results still get cached)}';

    protected $description = 'Fetch One Piece Card Game catalog data (English) from a pinned punk-records/vegapull snapshot and generate catalog v2 import CSVs, with a dry-run validation report';

    /** Pinned commit — see the source/schema analysis this command was built from. Bump deliberately, never silently track a moving branch. */
    private const PUNK_RECORDS_COMMIT = '29fed25ccd7013caa76653495701852981afd021';
    private const PUNK_RECORDS_TARBALL_URL = 'https://api.github.com/repos/buhbbl/punk-records/tarball/' . self::PUNK_RECORDS_COMMIT;
    private const CACHE_DIR = 'onepiece-cache';
    private const USER_AGENT = 'Cardora/1.0 (+https://cardora.gr; catalog importer)';

    /** Bandai's own catch-all buckets — never a real release/product, see class docblock. */
    private const CATCHALL_PACK_TITLES = ['Other Product Card', 'Promotion card'];
    private const CATCHALL_SET_KEY = 'onepiece-en-catchall-promo';

    private array $handles = [];
    private array $packs = []; // pack_id => raw pack row from packs.json
    private array $catchallPackIds = [];
    private array $realPackIds = []; // ordered ascending by pack_id

    // base_number => ['home_pack_id'=>?, 'home_is_synthetic'=>bool, 'gameplay'=>[...], 'card_key'=>..., 'variants'=>[source_variant_id => [...]]]
    private array $cards = [];

    private array $writtenSetKeys = [];
    private array $writtenReleaseKeys = [];
    private array $variantRowsBySourceId = []; // dedupe: source_variant_id => variant row (+ provenance packs)

    private int $sourceObjects = 0;
    private array $severeGameplayConflicts = []; // base numbers excluded from output pending manual review
    private array $textOnlyGameplayVariants = []; // wording-only differences, informational
    private int $sameBasesSamePack = 0;
    private int $variantsWithMultiPackProvenance = 0;
    private int $variantsWithRealPackMismatchToHome = 0; // -> release memberships created
    private int $cardsWithSyntheticHome = 0;
    private int $rarityDist = 0; // placeholder, real dist built as array below

    private array $rarityDistribution = [];
    private array $categoryDistribution = [];
    private array $sourceVariantKindDistribution = [];
    private array $missingImages = [];

    private array $setRows = [];
    private array $cardRows = [];
    private array $variantRows = [];
    private array $externalIdRows = [];
    private array $releaseRows = [];
    private array $releaseMembershipRows = [];

    private array $snapshotMeta = [];

    private const DON_SUPPLEMENTAL_DIR = 'database/data/onepiece-supplemental';

    private int $primaryCardCount = 0;
    private int $primaryVariantCount = 0;
    private int $donCardCount = 0;
    private int $donVariantCount = 0;
    private int $donReleaseMembershipCount = 0;
    private array $donCardsSupplemental = []; // card_key => row
    private array $donVariantsSupplemental = []; // list of rows
    private array $donReleaseMembershipsSupplemental = []; // list of rows
    private array $unresolvedStandardDonDesigns = []; // rows from the backlog CSV
    private array $unresolvedSpecialDonDesigns = []; // rows from the backlog CSV
    private array $orphanReleaseMemberships = [];

    private array $gameplayOverrideRows = []; // raw rows from supplemental_gameplay_overrides.csv
    private array $resolvedGameplayConflictBases = []; // base_number => true, conflicts that got an override applied
    private array $gameplayOverridesApplied = []; // base_number => [field => ['from'=>..., 'to'=>..., provenance...]]

    public function handle(): int
    {
        $outDir = rtrim((string) ($this->option('out') ?: storage_path('app/onepiece')), '/');
        if (! is_dir($outDir) && ! mkdir($outDir, 0755, true) && ! is_dir($outDir)) {
            $this->error("Could not create output directory: {$outDir}");

            return self::FAILURE;
        }

        $gitCommit = $this->currentGitCommit();
        $this->info("Importer version: {$gitCommit['hash']}" . ($gitCommit['dirty'] ? ' (dirty working tree)' : ''));

        $this->info('Resolving punk-records snapshot (pinned commit ' . substr(self::PUNK_RECORDS_COMMIT, 0, 7) . ')...');
        $dataDir = $this->resolveSnapshot();
        if ($dataDir === null) {
            $this->error('Could not resolve punk-records snapshot — aborting.');

            return self::FAILURE;
        }

        $this->loadPacks("{$dataDir}/english/packs.json");
        $this->info('Packs: ' . count($this->packs) . ' (' . count($this->catchallPackIds) . ' catch-all, ' . count($this->realPackIds) . ' real)');

        $this->info('Reading card objects...');
        $this->loadAllCards("{$dataDir}/english/cards");
        $this->info("Source card objects: {$this->sourceObjects}, base card numbers: " . count($this->cards));

        $this->applyGameplayOverrides();

        $this->resolveHomesAndBuildRows();
        $this->primaryCardCount = count($this->cardRows);
        $this->primaryVariantCount = count($this->variantRows);

        $this->loadDonSupplementalData();
        $this->buildDonRows();

        $this->openCsvHandles($outDir);
        $this->writeAllRows($outDir);
        $this->closeCsvHandles();

        $report = $this->buildReport($gitCommit);
        $this->printReport($report);
        file_put_contents("{$outDir}/validation_report.json", json_encode($report, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        $this->newLine();
        $this->info("CSVs + validation_report.json written to: {$outDir}");

        if (! $this->option('apply')) {
            $this->comment('Dry-run only — nothing was written to the database. Pass --apply to import (runs on PASS or PASS_WITH_WARNINGS, refused on FAIL).');

            return self::SUCCESS;
        }

        if ($report['status'] === 'FAIL') {
            $this->error('Validation FAILed — refusing to --apply.');

            return self::FAILURE;
        }

        $this->info("Validation {$report['status']} — running cardora:binder-import-v2...");
        $exit = $this->call('cardora:binder-import-v2', ['--path' => $outDir]);

        return $exit === 0 ? self::SUCCESS : self::FAILURE;
    }

    /**
     * Downloads (or reuses the cached) tarball of punk-records at the
     * pinned commit, extracts it, and returns the path to the extracted
     * root (containing english/, english-asia/, etc). Cached by commit
     * hash, not by a moving branch/URL.
     */
    private function resolveSnapshot(): ?string
    {
        $cacheRoot = storage_path('app/' . self::CACHE_DIR);
        $extractedDir = "{$cacheRoot}/punk-records-" . self::PUNK_RECORDS_COMMIT;
        $tarballPath = "{$cacheRoot}/punk-records-" . self::PUNK_RECORDS_COMMIT . '.tar.gz';
        $metaPath = "{$cacheRoot}/snapshot-meta.json";

        if (! $this->option('refresh-cache') && is_dir($extractedDir) && is_file($metaPath)) {
            $this->snapshotMeta = json_decode((string) file_get_contents($metaPath), true) ?? [];
            $this->snapshotMeta['source'] = 'cache';

            return $this->findExtractedRoot($extractedDir);
        }

        if (! is_dir($cacheRoot)) {
            mkdir($cacheRoot, 0755, true);
        }

        $this->info('Downloading punk-records tarball from GitHub...');
        $maxAttempts = 3;
        $body = null;
        for ($attempt = 1; $attempt <= $maxAttempts; $attempt++) {
            try {
                $response = Http::timeout(120)->withHeaders([
                    'User-Agent' => self::USER_AGENT,
                    'Accept' => 'application/vnd.github+json',
                ])->get(self::PUNK_RECORDS_TARBALL_URL);
                if ($response->successful()) {
                    $body = $response->body();

                    break;
                }
                $this->warn("  fetch failed (HTTP {$response->status()})");
            } catch (\Throwable $e) {
                $this->warn("  fetch failed: {$e->getMessage()}");
            }
            if ($attempt < $maxAttempts) {
                usleep(1_000_000 * (2 ** ($attempt - 1)));
            }
        }
        if ($body === null) {
            return null;
        }

        file_put_contents($tarballPath, $body);
        $sha256 = hash('sha256', $body);
        unset($body);

        if (is_dir($extractedDir)) {
            $this->deleteDirectory($extractedDir);
        }
        mkdir($extractedDir, 0755, true);
        $phar = new \PharData($tarballPath);
        $phar->extractTo($extractedDir);

        $this->snapshotMeta = [
            'source' => 'live',
            'repository' => 'github.com/buhbbl/punk-records',
            'commit' => self::PUNK_RECORDS_COMMIT,
            'tarball_url' => self::PUNK_RECORDS_TARBALL_URL,
            'tarball_sha256' => $sha256,
            'downloaded_at' => now()->toIso8601String(),
        ];
        file_put_contents($metaPath, json_encode($this->snapshotMeta, JSON_PRETTY_PRINT));

        return $this->findExtractedRoot($extractedDir);
    }

    /** GitHub tarballs extract into a single top-level dir named "<owner>-<repo>-<short-sha>". */
    private function findExtractedRoot(string $extractedDir): string
    {
        $entries = array_values(array_diff(scandir($extractedDir) ?: [], ['.', '..']));
        if (count($entries) === 1 && is_dir("{$extractedDir}/{$entries[0]}")) {
            return "{$extractedDir}/{$entries[0]}";
        }

        return $extractedDir;
    }

    private function deleteDirectory(string $dir): void
    {
        $items = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS), \RecursiveIteratorIterator::CHILD_FIRST);
        foreach ($items as $item) {
            $item->isDir() ? rmdir($item->getPathname()) : unlink($item->getPathname());
        }
        rmdir($dir);
    }

    private function loadPacks(string $packsJsonPath): void
    {
        $this->packs = json_decode((string) file_get_contents($packsJsonPath), true) ?? [];
        ksort($this->packs, SORT_STRING);

        foreach ($this->packs as $packId => $pack) {
            $title = $pack['raw_title'] ?? '';
            $isCatchall = false;
            foreach (self::CATCHALL_PACK_TITLES as $catchallTitle) {
                if (trim($title) === $catchallTitle) {
                    $isCatchall = true;

                    break;
                }
            }
            if ($isCatchall) {
                $this->catchallPackIds[$packId] = true;
            } else {
                $this->realPackIds[] = $packId;
            }
        }
    }

    private function loadAllCards(string $cardsDir): void
    {
        foreach ($this->packs as $packId => $pack) {
            $packDir = "{$cardsDir}/{$packId}";
            if (! is_dir($packDir)) {
                continue;
            }

            $filesInPack = [];
            foreach (glob("{$packDir}/*.json") as $file) {
                $card = json_decode((string) file_get_contents($file), true);
                if (! is_array($card) || ! isset($card['id'])) {
                    continue;
                }
                $this->sourceObjects++;
                $filesInPack[] = $card;
            }
            if (count($filesInPack) > 0) {
                // detect same-base-number appearing more than once within this one pack (pure informational)
                $basesSeen = [];
                foreach ($filesInPack as $card) {
                    $base = $this->baseNumberOf($card['id']);
                    $basesSeen[$base] = ($basesSeen[$base] ?? 0) + 1;
                }
                foreach ($basesSeen as $n) {
                    if ($n > 1) {
                        $this->sameBasesSamePack++;
                    }
                }
            }

            foreach ($filesInPack as $card) {
                $this->indexCard($card, $packId);
            }
        }
    }

    private function baseNumberOf(string $sourceId): string
    {
        if (preg_match('/^(.+)_([a-z]+)(\d+)$/', $sourceId, $m)) {
            return $m[1];
        }

        return $sourceId;
    }

    private function suffixOf(string $sourceId): array
    {
        if (preg_match('/^(.+)_([a-z]+)(\d+)$/', $sourceId, $m)) {
            return ['kind' => $m[2], 'num' => $m[3]];
        }

        return ['kind' => 'base', 'num' => null];
    }

    /** @param array<string,mixed> $card */
    /**
     * Fields whose divergence across occurrences of the same base number
     * is a serious signal (this might not really be "the same card" --
     * e.g. EB01-023's parallel has power=8000/counter=1000 vs the base's
     * power=6000/counter=null, found during the pre-importer audit). Kept
     * separate from wording-only fields, which genuinely do vary between
     * print runs in this game (Bandai issues real errata/text
     * clarifications on reprints -- confirmed by direct inspection, not
     * assumed) and are common enough (26 base numbers) that treating them
     * as fatal would block far more than it protects.
     */
    private const SEVERE_GAMEPLAY_FIELDS = ['name', 'category', 'colors', 'cost', 'counter', 'power', 'attributes'];
    private const TEXT_GAMEPLAY_FIELDS = ['effect', 'trigger', 'types'];

    /** Bandai's site leaks a handful of typographic character variants (fullwidth minus, U+2212 minus) inconsistently between scrapes of the same value -- cosmetically different, not a real content difference. */
    private function normalizeText(mixed $value): mixed
    {
        if (is_string($value)) {
            return str_replace(["\xef\xbc\x8d", "\xe2\x88\x92"], '-', $value);
        }
        if (is_array($value)) {
            return array_map([$this, 'normalizeText'], $value);
        }

        return $value;
    }

    private function indexCard(array $card, string $packId): void
    {
        $sourceId = $card['id'];
        $base = $this->baseNumberOf($sourceId);
        $suffix = $this->suffixOf($sourceId);

        $gameplay = $this->normalizeText([
            'name' => $card['name'] ?? '',
            'category' => $card['category'] ?? '',
            'colors' => $card['colors'] ?? [],
            'cost' => $card['cost'] ?? null,
            'counter' => $card['counter'] ?? null,
            'power' => $card['power'] ?? null,
            'effect' => $card['effect'] ?? '',
            'trigger' => $card['trigger'] ?? null,
            'types' => $card['types'] ?? [],
            'attributes' => $card['attributes'] ?? [],
            'block_number' => $card['block_number'] ?? null,
        ]);

        if (! isset($this->cards[$base])) {
            $this->cards[$base] = ['gameplay' => $gameplay, 'variants' => [], 'severe_conflict' => false];
        } elseif (! $this->cards[$base]['severe_conflict']) {
            // verify gameplay consistency across every occurrence of this base number rather than silently trusting the first one
            $existing = $this->cards[$base]['gameplay'];
            $comparable = $gameplay;
            unset($existing['block_number'], $comparable['block_number']); // block_number can legitimately differ for genuine reprints in a later block

            $severeDiff = false;
            $severeDiffFields = [];
            foreach (self::SEVERE_GAMEPLAY_FIELDS as $f) {
                if (json_encode($existing[$f] ?? null) !== json_encode($comparable[$f] ?? null)) {
                    $severeDiff = true;
                    $severeDiffFields[$f] = ['existing' => $existing[$f] ?? null, 'conflicting' => $comparable[$f] ?? null];
                }
            }
            $textDiff = false;
            foreach (self::TEXT_GAMEPLAY_FIELDS as $f) {
                if (json_encode($existing[$f] ?? null) !== json_encode($comparable[$f] ?? null)) {
                    $textDiff = true;

                    break;
                }
            }

            if ($severeDiff) {
                $this->cards[$base]['severe_conflict'] = true;
                $this->severeGameplayConflicts[] = [
                    'base' => $base,
                    'pack' => $packId,
                    'source_id' => $sourceId,
                    'conflicting_fields' => $severeDiffFields,
                ];
            } elseif ($textDiff) {
                $this->textOnlyGameplayVariants[] = ['base' => $base, 'pack' => $packId, 'source_id' => $sourceId];
            }
        }

        $img = preg_replace('/\?.*/', '', basename($card['img_url'] ?? ''));
        $rarity = $card['rarity'] ?? null;
        $this->rarityDistribution[$rarity ?? '(none)'] = ($this->rarityDistribution[$rarity ?? '(none)'] ?? 0) + 1;
        $this->categoryDistribution[$gameplay['category'] ?: '(none)'] = ($this->categoryDistribution[$gameplay['category'] ?: '(none)'] ?? 0) + 1;
        $this->sourceVariantKindDistribution[$suffix['kind']] = ($this->sourceVariantKindDistribution[$suffix['kind']] ?? 0) + 1;

        if (! isset($this->variantRowsBySourceId[$sourceId])) {
            $this->variantRowsBySourceId[$sourceId] = [
                'base' => $base,
                'source_variant_id' => $sourceId,
                'source_variant_kind' => $suffix['kind'],
                'rarity' => $rarity,
                'artist' => null, // not present in punk-records card schema
                'img_url' => $card['img_url'] ?? '',
                'img_full_url' => $card['img_full_url'] ?? '',
                'img_basename' => $img,
                'packs' => [],
                'real_packs' => [],
            ];
        }
        $this->variantRowsBySourceId[$sourceId]['packs'][$packId] = true;
        if (! isset($this->catchallPackIds[$packId])) {
            $this->variantRowsBySourceId[$sourceId]['real_packs'][$packId] = true;
        }
        if (empty($this->missingImages) || true) {
            if (($card['img_url'] ?? '') === '') {
                $this->missingImages[] = $sourceId;
            }
        }

        $this->cards[$base]['variants'][$sourceId] = true;
    }

    /**
     * Applies database/data/onepiece-supplemental/supplemental_gameplay_overrides.csv
     * -- a hand-researched, cross-checked correction to a base number's
     * canonical gameplay fields (never rarity/artwork, which stay
     * per-variant). Runs after loadAllCards() so every upstream conflict
     * has already been detected, and clears severe_conflict so the card is
     * no longer excluded once a verified resolution exists. The raw
     * conflicting source values stay in $severeGameplayConflicts for the
     * report regardless -- the override corrects the canonical record, it
     * doesn't erase the evidence of why one was needed.
     */
    private function applyGameplayOverrides(): void
    {
        $dir = base_path(self::DON_SUPPLEMENTAL_DIR);
        $this->gameplayOverrideRows = $this->readCsv("{$dir}/supplemental_gameplay_overrides.csv");

        $byBase = [];
        foreach ($this->gameplayOverrideRows as $row) {
            $byBase[$row['base_number']][] = $row;
        }

        foreach ($byBase as $base => $rows) {
            if (! isset($this->cards[$base])) {
                $this->warn("  supplemental_gameplay_overrides.csv: base number {$base} not found in source data — override NOT applied");

                continue;
            }

            foreach ($rows as $row) {
                $field = $row['field'];
                $from = $this->cards[$base]['gameplay'][$field] ?? null;
                $to = $row['value'] !== '' ? $row['value'] : null;
                if (in_array($field, ['cost', 'power', 'counter'], true) && $to !== null) {
                    $to = (int) $to;
                }
                $this->cards[$base]['gameplay'][$field] = $to;
                $this->gameplayOverridesApplied[$base][$field] = [
                    'from' => $from,
                    'to' => $to,
                    'source_provider' => $row['source_provider'],
                    'source_url' => $row['source_url'],
                    'verification_source' => $row['verification_source'],
                    'notes' => $row['notes'],
                ];
            }

            if ($this->cards[$base]['severe_conflict']) {
                $this->cards[$base]['severe_conflict'] = false;
                $this->resolvedGameplayConflictBases[$base] = true;
            }
        }
    }

    private function resolveHomesAndBuildRows(): void
    {
        // Synthetic catch-all Set, only registered if actually needed.
        $needsSyntheticSet = false;

        foreach ($this->cards as $base => &$cardData) {
            if ($cardData['severe_conflict']) {
                // a severe (non-textual) gameplay mismatch was found across this base number's occurrences --
                // excluded from the canonical catalog pending manual review, not silently merged or guessed.
                continue;
            }

            $variantSourceIds = array_keys($cardData['variants']);

            // home pack = first REAL pack (ascending, chronological-ish order) where ANY variant of this base appears
            $homePackId = null;
            foreach ($this->realPackIds as $packId) {
                foreach ($variantSourceIds as $sid) {
                    if (isset($this->variantRowsBySourceId[$sid]['packs'][$packId])) {
                        $homePackId = $packId;

                        break 2;
                    }
                }
            }

            $isSynthetic = $homePackId === null;
            if ($isSynthetic) {
                $needsSyntheticSet = true;
                $this->cardsWithSyntheticHome++;
            }

            $setKey = $isSynthetic ? self::CATCHALL_SET_KEY : $this->toSetKey($homePackId);
            $cardKey = $this->toCardKey($setKey, $base);

            $cardData['home_pack_id'] = $homePackId;
            $cardData['home_is_synthetic'] = $isSynthetic;
            $cardData['set_key'] = $setKey;
            $cardData['card_key'] = $cardKey;

            $this->cardRows[] = [
                'game_slug' => 'one-piece',
                'set_key' => $setKey,
                'card_key' => $cardKey,
                'card_name' => $cardData['gameplay']['name'],
                'clean_name' => $cardData['gameplay']['name'],
                'collector_number' => $base,
                'card_type' => $cardData['gameplay']['category'],
                'is_promo' => ($cardData['gameplay']['category'] === 'Promo' || str_starts_with($base, 'P-')) ? 'TRUE' : 'FALSE',
                'is_token' => 'FALSE',
                'language' => 'EN',
            ];

            $sortOrder = 1;
            foreach ($variantSourceIds as $sid) {
                $v = $this->variantRowsBySourceId[$sid];
                $variantKey = "{$cardKey}:{$sid}";

                $this->variantRows[] = [
                    'card_key' => $cardKey,
                    'variant_key' => $variantKey,
                    'source_variant_id' => $sid,
                    'source_variant_kind' => $v['source_variant_kind'],
                    'variant_name' => $v['source_variant_kind'] === 'base' ? 'Standard' : (ucfirst($v['source_variant_kind']) . ' ' . $this->suffixOf($sid)['num']),
                    'variant_type' => $v['source_variant_kind'],
                    'rarity' => $v['rarity'] ?? '',
                    'region_code' => '',
                    'edition_code' => '',
                    'artist' => '',
                    'image_small' => $v['img_full_url'],
                    'image_large' => $v['img_full_url'],
                    'sort_order' => $sortOrder++,
                ];

                // Provenance: catch-all bucket sightings (0, 1, or 2 -- both 569801+569901 for the one found duplicate)
                foreach (array_keys($v['packs']) as $packId) {
                    if (isset($this->catchallPackIds[$packId])) {
                        $this->externalIdRows[] = [
                            'entity_type' => 'variant',
                            'entity_key' => $variantKey,
                            'provider' => 'onepiece-cardgame',
                            'external_id' => $packId,
                            'external_type' => 'source_catchall_bucket',
                            'external_url' => '',
                        ];
                    }
                }
                $this->externalIdRows[] = [
                    'entity_type' => 'variant',
                    'entity_key' => $variantKey,
                    'provider' => 'onepiece-cardgame',
                    'external_id' => $sid,
                    'external_type' => 'source_variant_id',
                    'external_url' => '',
                ];
                if (count($v['packs']) > 1) {
                    $this->variantsWithMultiPackProvenance++;
                }

                // Release membership: for every REAL pack this variant appears in that ISN'T the card's home pack.
                $realPacksForVariant = array_keys($v['real_packs']);
                foreach ($realPacksForVariant as $packId) {
                    if ($packId === $homePackId) {
                        continue;
                    }
                    $this->variantsWithRealPackMismatchToHome++;
                    $releaseKey = $this->toSetKey($packId); // reuse the same key scheme -- a pack is both a Set (for its own native cards) and a Release (for foreign variants it hosts)
                    if (! isset($this->writtenReleaseKeys[$releaseKey])) {
                        $pack = $this->packs[$packId];
                        $this->releaseRows[] = [
                            'game_slug' => 'one-piece',
                            'release_key' => $releaseKey,
                            'release_name' => $pack['raw_title'] ?? $packId,
                            'release_type' => 'pack_product',
                            'region_code' => '',
                            'released_at' => '',
                            'source_provider' => 'onepiece-cardgame',
                            'source_external_id' => $packId,
                            'notes' => "Auto-generated release mirror of set {$releaseKey} -- hosts at least one variant whose canonical card is homed in a different pack.",
                        ];
                        $this->writtenReleaseKeys[$releaseKey] = true;
                    }
                    $this->releaseMembershipRows[] = [
                        'card_key' => $cardKey,
                        'variant_key' => $variantKey,
                        'release_key' => $releaseKey,
                        'membership_type' => 'reprint_or_parallel_in_product',
                        'source_provider' => 'onepiece-cardgame',
                        'source_reference' => $packId,
                        'notes' => "{$sid} appears in pack {$packId} (\"{$this->packs[$packId]['raw_title']}\"), distinct from {$cardKey}'s home pack {$homePackId}.",
                    ];
                }
            }
        }
        unset($cardData);

        // Register real Sets (every real pack that has at least one NATIVE card, i.e. is some base number's home)
        $setKeysNeeded = [];
        foreach ($this->cards as $cardData) {
            if ($cardData['severe_conflict']) {
                continue;
            }
            $setKeysNeeded[$cardData['set_key']] = true;
        }
        foreach ($this->realPackIds as $packId) {
            $setKey = $this->toSetKey($packId);
            if (! isset($setKeysNeeded[$setKey])) {
                continue; // no native cards homed here (shouldn't happen for real packs, but don't fabricate a set with 0 cards)
            }
            $pack = $this->packs[$packId];
            $this->setRows[$setKey] = [
                'game_slug' => 'one-piece',
                'set_key' => $setKey,
                'set_name' => $pack['raw_title'] ?? $packId,
                'abbreviation' => $pack['title_parts']['label'] ?? $packId,
                'set_code' => $pack['title_parts']['label'] ?? $packId,
                'set_type' => 'main',
                'language' => 'EN',
                'region' => '',
                'released_at' => '',
                'base_total' => '',
                'numbered_total' => '',
                'source' => 'onepiece-cardgame',
                'source_set_id' => $packId,
                'source_url' => '',
            ];
        }
        if ($needsSyntheticSet) {
            $this->setRows[self::CATCHALL_SET_KEY] = [
                'game_slug' => 'one-piece',
                'set_key' => self::CATCHALL_SET_KEY,
                'set_name' => 'English Promo / Other Product Cards (source catch-all)',
                'abbreviation' => 'PROMO',
                'set_code' => 'PROMO',
                'set_type' => 'promo_catchall',
                'language' => 'EN',
                'region' => '',
                'released_at' => '',
                'base_total' => '',
                'numbered_total' => '',
                'source' => 'onepiece-cardgame',
                'source_set_id' => '',
                'source_url' => '',
                'notes' => 'Synthetic structural grouping -- merges Bandai\'s own "Other Product Card" (569801) and "Promotion card" (569901) catch-all buckets for cards with no real home pack. Not a real release/product; do not treat as a canonical set for display purposes without review.',
            ];
        }
    }

    /** @return array<int,array<string,string>> */
    private function readCsv(string $path): array
    {
        if (! is_file($path)) {
            return [];
        }
        $handle = fopen($path, 'r');
        $header = fgetcsv($handle) ?: [];
        $rows = [];
        while (($row = fgetcsv($handle)) !== false) {
            if (count($row) !== count($header)) {
                $this->warn("  {$path}: column count mismatch, skipping row");

                continue;
            }
            $rows[] = array_combine($header, $row);
        }
        fclose($handle);

        return $rows;
    }

    /**
     * Loads the hand-researched, provenance-tracked DON!! supplemental
     * dataset -- see database/data/onepiece-supplemental/README.md. Never
     * inferred from artwork alone; every row here was verified against an
     * official Bandai product page plus a second independent source.
     */
    private function loadDonSupplementalData(): void
    {
        $dir = base_path(self::DON_SUPPLEMENTAL_DIR);

        foreach ($this->readCsv("{$dir}/supplemental_don_cards.csv") as $row) {
            $this->donCardsSupplemental[$row['card_key']] = $row;
        }
        $this->donVariantsSupplemental = $this->readCsv("{$dir}/supplemental_don_variants.csv");
        $this->donReleaseMembershipsSupplemental = $this->readCsv("{$dir}/supplemental_don_release_memberships.csv");
        $this->unresolvedStandardDonDesigns = $this->readCsv("{$dir}/unresolved_standard_don_designs.csv");
        $this->unresolvedSpecialDonDesigns = $this->readCsv("{$dir}/unresolved_special_don_designs.csv");
    }

    /**
     * Adds the 14 verified DON!! canonical cards / 16 variants on top of
     * the regular card pipeline. Each DON card's set_id is its home
     * release's Set (created here if the regular pipeline didn't already
     * register it, e.g. a product that hosts no *native* non-DON card of
     * its own); a variant-level release membership is also created for
     * every DON variant, per the locked mapping
     * (verified DON design -> supplemental binder_card -> verified DON
     * treatment -> binder_card_variant, physical release -> variant-level
     * membership).
     */
    private function buildDonRows(): void
    {
        foreach ($this->donCardsSupplemental as $cardKey => $row) {
            $releaseKey = $row['release_key'];
            $this->ensureSetForReleaseKey($releaseKey);

            $this->cardRows[] = [
                'game_slug' => 'one-piece',
                'set_key' => $releaseKey,
                'card_key' => $cardKey,
                'card_name' => $row['card_name'],
                'clean_name' => $row['card_name'],
                'collector_number' => '', // DON!! cards have no official collector number -- never invented, see unresolved_standard_don_designs.csv
                'card_type' => $row['card_type'],
                'is_promo' => 'TRUE',
                'is_token' => 'FALSE',
                'language' => 'EN',
            ];
            $this->donCardCount++;

            $this->externalIdRows[] = [
                'entity_type' => 'card',
                'entity_key' => $cardKey,
                'provider' => $row['source_provider'],
                'external_id' => $row['source_url'],
                'external_type' => 'verification_source_url',
                'external_url' => $row['source_url'],
            ];
        }

        foreach ($this->donVariantsSupplemental as $row) {
            if (! isset($this->donCardsSupplemental[$row['card_key']])) {
                $this->warn("  supplemental_don_variants.csv: unknown card_key {$row['card_key']} — skipping");

                continue;
            }
            $this->variantRows[] = [
                'card_key' => $row['card_key'],
                'variant_key' => $row['variant_key'],
                'source_variant_id' => $row['variant_key'],
                'source_variant_kind' => $row['variant_type'],
                'variant_name' => $row['variant_name'],
                'variant_type' => $row['variant_type'],
                'rarity' => '',
                'region_code' => '',
                'edition_code' => '',
                'artist' => '',
                'image_small' => '',
                'image_large' => '',
                'sort_order' => 1,
            ];
            $this->donVariantCount++;
        }

        $cardKeySet = array_flip(array_column($this->cardRows, 'card_key'));
        $variantKeySet = array_flip(array_column($this->variantRows, 'variant_key'));

        foreach ($this->donReleaseMembershipsSupplemental as $row) {
            $releaseKey = $row['release_key'];
            $this->ensureReleaseRow($releaseKey);

            if (! isset($cardKeySet[$row['card_key']]) || ! isset($variantKeySet[$row['variant_key']])) {
                $this->orphanReleaseMemberships[] = $row;

                continue;
            }

            $this->releaseMembershipRows[] = [
                'card_key' => $row['card_key'],
                'variant_key' => $row['variant_key'],
                'release_key' => $releaseKey,
                'membership_type' => $row['membership_type'],
                'source_provider' => $row['source_provider'],
                'source_reference' => $row['source_reference'],
                'notes' => $row['notes'],
            ];
            $this->donReleaseMembershipCount++;
        }
    }

    /** Registers a minimal Set row for a release_key if the regular pipeline hasn't already (a product with no *native* non-DON card of its own would otherwise never get one). */
    private function ensureSetForReleaseKey(string $setKey): void
    {
        if (isset($this->setRows[$setKey])) {
            return;
        }
        $packId = $this->packIdForSetKey($setKey);
        $pack = $packId !== null ? $this->packs[$packId] : null;

        $this->setRows[$setKey] = [
            'game_slug' => 'one-piece',
            'set_key' => $setKey,
            'set_name' => $pack['raw_title'] ?? $setKey,
            'abbreviation' => $pack['title_parts']['label'] ?? $setKey,
            'set_code' => $pack['title_parts']['label'] ?? $setKey,
            'set_type' => 'main',
            'language' => 'EN',
            'region' => '',
            'released_at' => '',
            'base_total' => '',
            'numbered_total' => '',
            'source' => 'onepiece-cardgame',
            'source_set_id' => $packId ?? '',
            'source_url' => '',
        ];
    }

    /** Registers a minimal Release row for a release_key if the regular pipeline hasn't already (a product with no reprinted-elsewhere-card variant would otherwise never trigger one). */
    private function ensureReleaseRow(string $releaseKey): void
    {
        if (isset($this->writtenReleaseKeys[$releaseKey])) {
            return;
        }
        $packId = $this->packIdForSetKey($releaseKey);
        $pack = $packId !== null ? $this->packs[$packId] : null;

        $this->releaseRows[] = [
            'game_slug' => 'one-piece',
            'release_key' => $releaseKey,
            'release_name' => $pack['raw_title'] ?? $releaseKey,
            'release_type' => 'pack_product',
            'region_code' => '',
            'released_at' => '',
            'source_provider' => 'onepiece-cardgame',
            'source_external_id' => $packId ?? '',
            'notes' => 'Registered via DON!! supplemental data (variant-level release membership) rather than the regular reprint-detection pipeline.',
        ];
        $this->writtenReleaseKeys[$releaseKey] = true;
    }

    private function packIdForSetKey(string $setKey): ?string
    {
        foreach ($this->realPackIds as $packId) {
            if ($this->toSetKey($packId) === $setKey) {
                return $packId;
            }
        }

        return null;
    }

    private function toSetKey(string $packId): string
    {
        $pack = $this->packs[$packId] ?? null;
        $label = $pack['title_parts']['label'] ?? $packId;

        return 'onepiece-en-' . $this->slug($label !== '' ? $label : $packId);
    }

    private function toCardKey(string $setKey, string $base): string
    {
        return "{$setKey}-" . $this->slug($base);
    }

    private function slug(string $value): string
    {
        return strtolower(preg_replace('/[^A-Za-z0-9]+/', '-', $value));
    }

    private function openCsvHandles(string $outDir): void
    {
        $this->handles['games'] = fopen("{$outDir}/games.csv", 'w');
        fputcsv($this->handles['games'], ['slug', 'name', 'category', 'sort_order']);
        fputcsv($this->handles['games'], ['one-piece', 'One Piece Card Game', 'tcg', 40]);
        fclose($this->handles['games']);
        unset($this->handles['games']);

        $this->handles['sets'] = fopen("{$outDir}/sets.csv", 'w');
        fputcsv($this->handles['sets'], [
            'game_slug', 'set_key', 'set_name', 'abbreviation', 'set_code', 'set_type', 'language',
            'region', 'released_at', 'base_total', 'numbered_total', 'source', 'source_set_id', 'source_url',
        ]);

        $this->handles['cards'] = fopen("{$outDir}/cards.csv", 'w');
        fputcsv($this->handles['cards'], [
            'game_slug', 'set_key', 'card_key', 'card_name', 'clean_name', 'collector_number',
            'card_type', 'is_promo', 'is_token', 'language',
        ]);

        $this->handles['variants'] = fopen("{$outDir}/variants.csv", 'w');
        fputcsv($this->handles['variants'], [
            'card_key', 'variant_key', 'source_variant_id', 'source_variant_kind', 'variant_name', 'variant_type',
            'rarity', 'region_code', 'edition_code', 'artist', 'image_small', 'image_large', 'sort_order',
        ]);

        $this->handles['external_ids'] = fopen("{$outDir}/external_ids.csv", 'w');
        fputcsv($this->handles['external_ids'], [
            'entity_type', 'entity_key', 'provider', 'external_id', 'external_type', 'external_url',
        ]);

        $this->handles['releases'] = fopen("{$outDir}/releases.csv", 'w');
        fputcsv($this->handles['releases'], [
            'game_slug', 'release_key', 'release_name', 'release_type', 'region_code', 'released_at', 'source_provider', 'source_external_id', 'notes',
        ]);

        $this->handles['release_memberships'] = fopen("{$outDir}/release_memberships.csv", 'w');
        fputcsv($this->handles['release_memberships'], [
            'card_key', 'variant_key', 'release_key', 'membership_type', 'source_provider', 'source_reference', 'notes',
        ]);
    }

    private function closeCsvHandles(): void
    {
        foreach ($this->handles as $handle) {
            fclose($handle);
        }
        $this->handles = [];
    }

    private function writeAllRows(string $outDir): void
    {
        foreach ($this->setRows as $row) {
            fputcsv($this->handles['sets'], [
                $row['game_slug'], $row['set_key'], $row['set_name'], $row['abbreviation'], $row['set_code'],
                $row['set_type'], $row['language'], $row['region'], $row['released_at'], $row['base_total'],
                $row['numbered_total'], $row['source'], $row['source_set_id'], $row['source_url'],
            ]);
        }
        foreach ($this->cardRows as $row) {
            fputcsv($this->handles['cards'], array_values($row));
        }
        foreach ($this->variantRows as $row) {
            fputcsv($this->handles['variants'], array_values($row));
        }
        foreach ($this->externalIdRows as $row) {
            fputcsv($this->handles['external_ids'], array_values($row));
        }
        foreach ($this->releaseRows as $row) {
            fputcsv($this->handles['releases'], [
                $row['game_slug'], $row['release_key'], $row['release_name'], $row['release_type'], $row['region_code'],
                $row['released_at'], $row['source_provider'], $row['source_external_id'], $row['notes'],
            ]);
        }
        foreach ($this->releaseMembershipRows as $row) {
            fputcsv($this->handles['release_memberships'], array_values($row));
        }
    }

    /** @return array{hash: string, short: string, dirty: bool} */
    private function currentGitCommit(): array
    {
        $repoDir = escapeshellarg(base_path());
        $hash = trim((string) shell_exec("git -C {$repoDir} rev-parse HEAD 2>&1"));
        $short = trim((string) shell_exec("git -C {$repoDir} rev-parse --short HEAD 2>&1"));
        $dirty = trim((string) shell_exec("git -C {$repoDir} status --porcelain -- app/Console/Commands/ImportOnePiece.php 2>&1")) !== '';

        return [
            'hash' => str_starts_with($hash, 'fatal') ? 'unknown' : $hash,
            'short' => str_starts_with($short, 'fatal') ? 'unknown' : $short,
            'dirty' => $dirty,
        ];
    }

    private function duplicates(array $values): array
    {
        $counts = array_count_values($values);

        return array_keys(array_filter($counts, fn ($n) => $n > 1));
    }

    /** @param array{hash:string,short:string,dirty:bool} $gitCommit */
    private function buildReport(array $gitCommit): array
    {
        $setKeys = array_column($this->setRows, 'set_key');
        $cardKeys = array_column($this->cardRows, 'card_key');
        $variantKeys = array_column($this->variantRows, 'variant_key');

        $duplicateSetKeys = $this->duplicates($setKeys);
        $duplicateCardKeys = $this->duplicates($cardKeys);
        $duplicateVariantKeys = $this->duplicates($variantKeys);

        $setKeySet = array_flip($setKeys);
        $orphanCards = array_values(array_filter($this->cardRows, fn ($c) => ! isset($setKeySet[$c['set_key']])));
        $cardKeySet = array_flip($cardKeys);
        $orphanVariants = array_values(array_filter($this->variantRows, fn ($v) => ! isset($cardKeySet[$v['card_key']])));

        // upstream_gameplay_conflicts: every base number where source occurrences ever disagreed on a severe
        // (non-textual) gameplay field -- historical evidence, kept regardless of whether it was later resolved.
        $upstreamConflictBases = array_unique(array_column($this->severeGameplayConflicts, 'base'));
        $resolvedConflictBases = array_keys($this->resolvedGameplayConflictBases);
        $unresolvedConflictBases = array_diff($upstreamConflictBases, $resolvedConflictBases);
        $textVariantBases = array_unique(array_column($this->textOnlyGameplayVariants, 'base'));

        $failCounts = [
            'duplicate_set_keys' => count($duplicateSetKeys),
            'duplicate_card_keys' => count($duplicateCardKeys),
            'duplicate_variant_keys' => count($duplicateVariantKeys),
            'orphan_cards' => count($orphanCards),
            'orphan_variants' => count($orphanVariants),
            'orphan_release_memberships' => count($this->orphanReleaseMemberships),
        ];

        $variantLevelReleaseMemberships = count(array_filter($this->releaseMembershipRows, fn ($m) => ($m['variant_key'] ?? '') !== ''));
        $unresolvedStandardDonCount = array_sum(array_column($this->unresolvedStandardDonDesigns, 'estimated_count'));
        $unresolvedSpecialDonCount = array_sum(array_column($this->unresolvedSpecialDonDesigns, 'estimated_count'));
        // importer_missing_images: images are always carried through verbatim from the source object, never
        // derived/transformed, so there's no code path that could lose an image that was actually present upstream.
        $importerMissingImages = 0;
        $warningCounts = [
            'missing_images' => count($this->missingImages),
            'cards_with_synthetic_home' => $this->cardsWithSyntheticHome,
            'unresolved_gameplay_conflicts' => count($unresolvedConflictBases),
            'text_only_gameplay_variants' => count($textVariantBases),
        ];

        $status = match (true) {
            array_sum($failCounts) > 0 => 'FAIL',
            array_sum($warningCounts) > 0 => 'PASS_WITH_WARNINGS',
            default => 'PASS',
        };

        return [
            'status' => $status,
            'importer_git_commit' => $gitCommit['hash'],
            'importer_git_commit_short' => $gitCommit['short'],
            'importer_working_tree_dirty' => $gitCommit['dirty'],
            'snapshot' => $this->snapshotMeta,

            'total_packs' => count($this->packs),
            'catchall_packs' => count($this->catchallPackIds),
            'real_packs' => count($this->realPackIds),
            'source_card_objects' => $this->sourceObjects,

            'generated_sets' => count($this->setRows),
            'generated_cards' => count($this->cardRows),
            'generated_variants' => count($this->variantRows),
            'generated_releases' => count($this->releaseRows),
            'generated_release_memberships' => count($this->releaseMembershipRows),

            'primary_cards' => $this->primaryCardCount,
            'primary_variants' => $this->primaryVariantCount,
            'supplemental_don_cards' => $this->donCardCount,
            'supplemental_don_variants' => $this->donVariantCount,

            'unique_base_card_numbers' => count($this->cards),
            'p_variants' => $this->sourceVariantKindDistribution['p'] ?? 0,
            'r_variants' => $this->sourceVariantKindDistribution['r'] ?? 0,

            'release_memberships' => count($this->releaseMembershipRows),
            'variant_level_release_memberships' => $variantLevelReleaseMemberships,
            'exact_duplicate_source_objects_deduped' => $this->variantsWithMultiPackProvenance,

            'unresolved_standard_don_designs' => $unresolvedStandardDonCount,
            'unresolved_standard_don_designs_detail' => $this->unresolvedStandardDonDesigns,
            'unresolved_special_don_designs' => $unresolvedSpecialDonCount,
            'unresolved_special_don_designs_buckets' => count($this->unresolvedSpecialDonDesigns),

            'duplicate_set_keys' => $duplicateSetKeys,
            'duplicate_card_keys' => $duplicateCardKeys,
            'duplicate_variant_keys' => $duplicateVariantKeys,
            'orphan_cards' => array_column($orphanCards, 'card_key'),
            'orphan_variants' => array_column($orphanVariants, 'variant_key'),
            'orphan_release_memberships' => $this->orphanReleaseMemberships,
            'importer_missing_images' => $importerMissingImages,

            'upstream_gameplay_conflicts' => count($upstreamConflictBases),
            'resolved_gameplay_conflicts' => count($resolvedConflictBases),
            'unresolved_gameplay_conflicts' => count($unresolvedConflictBases),
            'gameplay_conflict_raw_evidence' => $this->severeGameplayConflicts,
            'gameplay_overrides_applied' => $this->gameplayOverridesApplied,
            'unresolved_gameplay_conflict_bases' => array_values($unresolvedConflictBases),
            'text_only_gameplay_variants' => $textVariantBases,
            'text_only_gameplay_variant_examples' => array_slice($this->textOnlyGameplayVariants, 0, 30),

            'cards_with_synthetic_home' => $this->cardsWithSyntheticHome,
            'variants_with_multi_pack_provenance' => $this->variantsWithMultiPackProvenance,
            'variants_needing_release_membership' => $this->variantsWithRealPackMismatchToHome,
            'same_base_multiple_times_in_one_pack' => $this->sameBasesSamePack,

            'rarity_distribution' => $this->rarityDistribution,
            'category_distribution' => $this->categoryDistribution,
            'source_variant_kind_distribution' => $this->sourceVariantKindDistribution,

            'missing_images' => $this->missingImages,
        ];
    }

    private function printReport(array $r): void
    {
        $this->newLine();
        $this->info("=== Validation report (importer {$r['importer_git_commit_short']}) ===");
        $this->table(['Metric', 'Value'], [
            ['total_packs', $r['total_packs']],
            ['catchall_packs', $r['catchall_packs']],
            ['real_packs', $r['real_packs']],
            ['source_card_objects', $r['source_card_objects']],
            ['generated_sets', $r['generated_sets']],
            ['generated_cards', $r['generated_cards']],
            ['generated_variants', $r['generated_variants']],
            ['generated_releases', $r['generated_releases']],
            ['generated_release_memberships', $r['generated_release_memberships']],
            ['primary_cards', $r['primary_cards']],
            ['primary_variants', $r['primary_variants']],
            ['supplemental_don_cards', $r['supplemental_don_cards']],
            ['supplemental_don_variants', $r['supplemental_don_variants']],
            ['unique_base_card_numbers', $r['unique_base_card_numbers']],
            ['p_variants', $r['p_variants']],
            ['r_variants', $r['r_variants']],
            ['release_memberships', $r['release_memberships']],
            ['variant_level_release_memberships', $r['variant_level_release_memberships']],
            ['exact_duplicate_source_objects_deduped', $r['exact_duplicate_source_objects_deduped']],
            ['unresolved_standard_don_designs', $r['unresolved_standard_don_designs']],
            ['unresolved_special_don_designs', $r['unresolved_special_don_designs']],
            ['duplicate_set_keys (FAIL)', count($r['duplicate_set_keys'])],
            ['duplicate_card_keys (FAIL)', count($r['duplicate_card_keys'])],
            ['duplicate_variant_keys (FAIL)', count($r['duplicate_variant_keys'])],
            ['orphan_cards (FAIL)', count($r['orphan_cards'])],
            ['orphan_variants (FAIL)', count($r['orphan_variants'])],
            ['orphan_release_memberships (FAIL)', count($r['orphan_release_memberships'])],
            ['importer_missing_images (FAIL)', $r['importer_missing_images']],
            ['upstream_gameplay_conflicts', $r['upstream_gameplay_conflicts']],
            ['resolved_gameplay_conflicts', $r['resolved_gameplay_conflicts']],
            ['unresolved_gameplay_conflicts (WARNING, excluded from output)', $r['unresolved_gameplay_conflicts']],
            ['text_only_gameplay_variants (WARNING, kept as-is)', count($r['text_only_gameplay_variants'])],
            ['cards_with_synthetic_home (WARNING)', $r['cards_with_synthetic_home']],
            ['variants_with_multi_pack_provenance', $r['variants_with_multi_pack_provenance']],
            ['variants_needing_release_membership', $r['variants_needing_release_membership']],
            ['same_base_multiple_times_in_one_pack', $r['same_base_multiple_times_in_one_pack']],
            ['missing_images (WARNING)', count($r['missing_images'])],
            ['STATUS', $r['status']],
        ]);

        $this->newLine();
        $this->comment('Rarity distribution:');
        $rar = $r['rarity_distribution'];
        arsort($rar);
        foreach ($rar as $k => $v) $this->line("  {$k}: {$v}");

        $this->newLine();
        $this->comment('Category distribution:');
        foreach ($r['category_distribution'] as $k => $v) $this->line("  {$k}: {$v}");

        $this->newLine();
        $this->comment('source_variant_kind distribution:');
        foreach ($r['source_variant_kind_distribution'] as $k => $v) $this->line("  {$k}: {$v}");

        if ($r['gameplay_conflict_raw_evidence'] !== []) {
            $this->newLine();
            $this->comment('Gameplay conflicts found (raw conflicting source values):');
            foreach ($r['gameplay_conflict_raw_evidence'] as $e) {
                $resolved = isset($r['gameplay_overrides_applied'][$e['base']]) ? 'RESOLVED via supplemental override' : 'UNRESOLVED — excluded from output';
                $this->line("  {$e['base']} @ pack {$e['pack']} (source_id={$e['source_id']}) — {$resolved}");
                foreach ($e['conflicting_fields'] ?? [] as $field => $vals) {
                    $this->line('    ' . $field . ': ' . json_encode($vals['existing']) . ' vs ' . json_encode($vals['conflicting']));
                }
            }
            if ($r['gameplay_overrides_applied'] !== []) {
                $this->newLine();
                $this->comment('Overrides applied:');
                foreach ($r['gameplay_overrides_applied'] as $base => $fields) {
                    foreach ($fields as $field => $o) {
                        $this->line("  {$base}.{$field}: " . json_encode($o['from']) . ' -> ' . json_encode($o['to']) . " ({$o['verification_source']})");
                    }
                }
            }
        }

        if ($r['text_only_gameplay_variant_examples'] !== []) {
            $this->newLine();
            $this->warn('Text-only gameplay variants (effect/trigger/types wording differs -- kept as one canonical card, using its home pack\'s text; likely genuine errata between print runs):');
            foreach ($r['text_only_gameplay_variant_examples'] as $e) {
                $this->line("  {$e['base']} @ pack {$e['pack']} (source_id={$e['source_id']})");
            }
        }
    }
}
